name: 'nl_vehicle_warehouse'
version: '1.0.0'
config-version: 2

profile: 'nl_vehicle_warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nl_vehicle_warehouse:
    staging:
      +materialized: view
    warehouse:
      +materialized: table
    marts:
      +materialized: table
